Refactor whole plugin code
helloideabox/easy-coupons pull request #5
Opened 2020-11-18 10:09 UTC by kishanjasani

2020-11-25 20:15 UTC, kishanjasani commented
GitHub API communication error. Please contact a human. (commit-ID: d25b2305ac214de79b6b8b6860ffae7c9f57e408).

2020-11-26 06:55 UTC, jkbot-code requested changes
**phpcs** scanning turned up:

:no_entry_sign: 150 errors 

:warning: 10 warnings 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

2020-11-26 06:55 UTC, jkbot-code commented on templates/taxonomy-easy-coupons-cat.php
> +									$coupon = sprintf( _n( '%d Coupon', '%d Coupons', $t->count, 'easy-coupons' ), number_format_i18n( $t->count ) );
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on templates/easy-coupons-coupon.php
>  		// Trim coupon code for Reveal style
:no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

2020-11-26 06:55 UTC, jkbot-code commented on templates/easy-coupons-coupon.php
> +		<span class="ibx-ec-coupon-copy-text"><?php esc_attr_e( 'Copy', 'easy-coupons' ); ?></span>
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on templates/easy-coupons-archive-template.php
>  			$paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;
:no_entry_sign: **Error**: Overriding WordPress globals is prohibited. Found assignment to $paged (*WordPress.WP.GlobalVariablesOverride.Prohibited*).

2020-11-26 06:55 UTC, jkbot-code commented on templates/easy-coupons-archive-template.php
> +				<li class="active ibx-ec-filter-coupon" data-filter="all"><a href="#"><?php esc_html_e( 'All', 'easy-coupons' ); ?></a></li>
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  		</Fragment>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  		</Fragment>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  		</Fragment>
:no_entry_sign: **Error**: Expected 1 space before &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  		</Fragment>
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space before &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  				/>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  				/>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					max={4}
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					max={4}
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					max={4}
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 16 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					min={2}
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					min={2}
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
> +					min={2}
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 16 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					value={ gridColumns }
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					value={ gridColumns }
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					value={ gridColumns }
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 14 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					shiftStep={ 1 }
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					shiftStep={ 1 }
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					shiftStep={ 1 }
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 10 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					onChange={ setGridColumns }
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					onChange={ setGridColumns }
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/sections/layout/GridLayoutSettings.js
>  					onChange={ setGridColumns }
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 11 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  				className="mt-6 mb-3"
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  				className="mt-6 mb-3"
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  				className="mt-6 mb-3"
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 14 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<Button
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space before &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space before &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space after &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			<div>{ 'grid' === couponLayout ? <GridLayoutSettings /> : null }</div>
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space before &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  			</BaseControl>
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  				/>
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  				/>
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  					value={ postPerPage }
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  					value={ postPerPage }
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/tabs/CouponsPage.js
>  					value={ postPerPage }
:warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 14 spaces but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  }, 0 );
:no_entry_sign: **Error**: Closing parenthesis of a multi-line function call must be on a line by itself (*PEAR.Functions.FunctionCallSignature.CloseBracketLine*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  }, 0 );
:no_entry_sign: **Error**: Only one argument is allowed per line in a multi-line function call (*PEAR.Functions.FunctionCallSignature.MultipleArguments*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space before &quot;=&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:warning: **Warning**: Equals sign not aligned correctly; expected 1 space but found 0 spaces (*Generic.Formatting.MultipleStatementAlignment.IncorrectWarning*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  		<App hideLoader={ hideLoader } showLoader={ showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 06:55 UTC, jkbot-code commented on src/settings/index.js
>  setTimeout( () => {
:no_entry_sign: **Error**: Opening parenthesis of a multi-line function call must be the last content on the line (*PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +		echo $excerpt;
:no_entry_sign: **Error**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$excerpt' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2020-11-26 06:55 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +	 * @param  string $layout Coupons layout.
:no_entry_sign: **Error**: Doc comment for parameter $layout does not match actual variable name $limit (*Squiz.Commenting.FunctionComment.ParamNameNoMatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +	 * @param  mixed  $count  Coupons count.
:no_entry_sign: **Error**: Doc comment for parameter $count does not match actual variable name $coupon_excerpt (*Squiz.Commenting.FunctionComment.ParamNameNoMatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +	/**
:no_entry_sign: **Error**: Doc comment for parameter &quot;$limit&quot; missing (*Squiz.Commenting.FunctionComment.MissingParamTag*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +	/**
:no_entry_sign: **Error**: Doc comment for parameter &quot;$coupon_excerpt&quot; missing (*Squiz.Commenting.FunctionComment.MissingParamTag*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				esc_html_e( 'No coupons found.', 'easy-coupons' );
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +									// Trim coupon code for Reveal style
:no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +									<span class="ibx-ec-coupon-copy-text"><?php esc_attr_e( 'Copy', 'easy-coupons' ); ?></span>
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'    => __( 'Typography', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Text Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:55 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Coupons Description', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'list' => __( 'List', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Layout', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'description' => __( 'Leave blank to show all coupons', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'       => __( 'Coupons Count', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'description'  => __( 'To Setup: Go to -> Easy Coupon Setting -> Layout', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'        => __( 'Use Global Options', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Coupons Setting', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Excerpt Length', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label_off'    => __( 'No', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label_on'     => __( 'Yes', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'        => __( 'Coupon Excerpt', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'   => __( 'Image Size', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Fallback Image Custom', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'custom'      => __( 'Custom', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'placeholder' => __( 'Placeholder', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +					''            => __( 'None', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Fallback Image', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'description' => __( 'Leave blank to show full title', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'title'       => __( 'In characters', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'       => __( 'Coupon Title Length', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label_off'    => __( 'No', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label_on'     => __( 'Yes', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'        => __( 'Coupons Title', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +						'title' => __( 'Right', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +						'title' => __( 'Center', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +						'title' => __( 'Left', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'       => __( 'Text Alignment', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Layout', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +		return __( 'Easy Coupons', 'easy-coupons' );
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +class Easy_Coupons_Widget extends Widget_Base {
:no_entry_sign: **Error**: Missing doc comment for class Easy_Coupons_Widget (*Squiz.Commenting.ClassComment.Missing*).

2020-11-26 06:56 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:56 UTC, jkbot-code commented on page-builders/elementor/class-easy-coupons-widget.php
> +<?php
:no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

2020-11-26 06:56 UTC, jkbot-code commented on easy-coupons.php
>  	$message      = sprintf( esc_html__( 'Easy Coupons requires WordPress version %s+. Because you are using an earlier version, the plugin is currently NOT RUNNING.', 'easy-coupons' ), '5.0' );
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on easy-coupons.php
>  	$message      = sprintf( esc_html__( 'Easy Coupons requires PHP version %s+, plugin is currently NOT RUNNING.', 'easy-coupons' ), '5.6' );
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:56 UTC, jkbot-code commented on easy-coupons.php
>   */
:no_entry_sign: **Error**: There must be no blank lines after the function comment (*Squiz.Commenting.FunctionComment.SpacingAfter*).

2020-11-26 06:56 UTC, jkbot-code commented on classes/plugin.php
> +		if ( ! wp_verify_nonce( $_POST['nonce'], 'ibx_ec_infinite_scroll_nonce' ) ) {
:no_entry_sign: **Error**: Detected usage of a non-sanitized input variable: $_POST['nonce'] (*WordPress.Security.ValidatedSanitizedInput.InputNotSanitized*).

2020-11-26 06:56 UTC, jkbot-code commented on classes/plugin.php
> +		if ( ! wp_verify_nonce( $_POST['nonce'], 'ibx_ec_infinite_scroll_nonce' ) ) {
:no_entry_sign: **Error**: $_POST data not unslashed before sanitization. Use wp_unslash() or similar (*WordPress.Security.ValidatedSanitizedInput.MissingUnslash*).

2020-11-26 06:56 UTC, jkbot-code commented on classes/plugin.php
> +		if ( ! wp_verify_nonce( $_POST['nonce'], 'ibx_ec_infinite_scroll_nonce' ) ) {
:no_entry_sign: **Error**: Detected usage of a possibly undefined superglobal array index: $_POST['nonce']. Use isset() or empty() to check the index exists before using it (*WordPress.Security.ValidatedSanitizedInput.InputNotValidated*).

2020-11-26 06:56 UTC, jkbot-code commented on classes/plugin.php
>  	public function ec_infinitepaginate() {
:no_entry_sign: **Error**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2020-11-26 06:56 UTC, jkbot-code commented on classes/admin-settings.php
> +			wp_enqueue_style( 'jquery-ui-datepicker-style', EASY_COUPONS_URL . 'assets/css/jquery-ui.css' );
:no_entry_sign: **Error**: Resource version not set in call to wp_enqueue_style(). This means new versions of the style will not always be loaded due to browser caching (*WordPress.WP.EnqueuedResourceParameters.MissingVersion*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/coupons-block/coupons-block.php
> +function ibx_ec_blocks_render_coupons_block( $attributes ) {
:no_entry_sign: **Error**: Missing doc comment for function ibx_ec_blocks_render_coupons_block() (*Squiz.Commenting.FunctionComment.Missing*).

2020-11-26 06:56 UTC, jkbot-code requested changes
Previous scan continued.

2020-11-26 06:56 UTC, jkbot-code commented on assets/coupons-block/coupons-block.php
>  	wp_register_script(
:no_entry_sign: **Error**: Resource version not set in call to wp_register_script(). This means new versions of the script will not always be loaded due to browser caching (*WordPress.WP.EnqueuedResourceParameters.MissingVersion*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/coupons-block/coupons-block.php
>  	wp_register_script(
:warning: **Warning**: In footer ($in_footer) is not set explicitly wp_register_script; It is recommended to load scripts in the footer. Please set this value to `true` to load it in the footer, or explicitly `false` if it should be loaded in the header (*WordPress.WP.EnqueuedResourceParameters.NotInFooter*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/coupons-block/coupons-block.php
> +function ibx_ec_blocks_register_block_type( $block, $options = array() ) {
:no_entry_sign: **Error**: Missing doc comment for function ibx_ec_blocks_register_block_type() (*Squiz.Commenting.FunctionComment.Missing*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/coupons-block/coupons-block.php
>   * @param [type] $post
:no_entry_sign: **Error**: Missing parameter comment (*Squiz.Commenting.FunctionComment.MissingParamComment*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.js
> \ No newline at end of file
:warning: **Warning**: File appears to be minified and cannot be processed (*Internal.Tokenizer.Exception*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: File must end with a newline character (*Generic.Files.EndFileNewline.NotFound*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: When a multi-item array uses associative keys, each value should start on a new line (*WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space before array closer (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space after array opener (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener*).

2020-11-26 06:56 UTC, jkbot-code commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

2020-11-26 06:56 UTC, jkbot-code commented
GitHub API communication error. Please contact a human. (commit-ID: d25b2305ac214de79b6b8b6860ffae7c9f57e408).

2020-11-26 06:59 UTC, ideaboxgit requested changes
**phpcs** scanning turned up:

:no_entry_sign: 46 errors 

:warning: 1 warning 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Coupon Code Background', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Coupon Code Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'    => __( 'Typography', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Discount Background Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Discount Text Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Coupons Meta', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'      => __( 'Margin Bottom', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Typography', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Text Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Coupon Title', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit requested changes
Previous scan continued.

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'      => __( 'Padding', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'    => __( 'Post Content Background', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Content', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'      => __( 'Margin Bottom', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'    => __( 'Typography', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Text Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Main Title', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +	 */
:no_entry_sign: **Error**: Expected 9 space(s) before asterisk; 5 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +	 * Style Tab: Main Title
:no_entry_sign: **Error**: Expected 9 space(s) before asterisk; 5 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'      => __( 'Border Radius', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit requested changes
Previous scan continued.

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'       => __( 'Border', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Background Color', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Tiles', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label' => __( 'Layout', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'span' => __( 'SPAN', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'p'    => __( 'P', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'div'  => __( 'DIV', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h6'   => __( 'H6', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h5'   => __( 'H5', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h4'   => __( 'H4', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit requested changes
Previous scan continued.

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h3'   => __( 'H3', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h2'   => __( 'H2', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'h1'   => __( 'H1', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Coupon Title Tag', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'        => __( 'Show Discount', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'4' => __( '4', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'3' => __( '3', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'2' => __( '2', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +				'label'     => __( 'Columns', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit commented on page-builders/elementor/class-easy-coupons-widget.php
> +					'grid' => __( 'Grid', 'easy-coupons' ),
:no_entry_sign: **Error**: Mismatched text domain. Expected 'EasyCoupons' but got 'easy-coupons' (*WordPress.WP.I18n.TextDomainMismatch*).

2020-11-26 06:59 UTC, ideaboxgit requested changes
Previous scan continued.

2020-11-26 06:59 UTC, ideaboxgit commented on classes/plugin.php
>  	public function ec_infinitepaginate() {
:no_entry_sign: **Error**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.js
> \ No newline at end of file
:warning: **Warning**: File appears to be minified and cannot be processed (*Internal.Tokenizer.Exception*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: File must end with a newline character (*Generic.Files.EndFileNewline.NotFound*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: When a multi-item array uses associative keys, each value should start on a new line (*WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space before array closer (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space after array opener (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener*).

2020-11-26 06:59 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

2020-11-26 08:09 UTC, ideaboxgit requested changes
**phpcs** scanning turned up:

:no_entry_sign: 15 errors 

:warning: 1 warning 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

2020-11-26 08:09 UTC, ideaboxgit commented on src/settings/index.js
> +			<App hideLoader = { hideLoader } showLoader = { showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 08:09 UTC, ideaboxgit commented on src/settings/index.js
> +			<App hideLoader = { hideLoader } showLoader = { showLoader } />,
:no_entry_sign: **Error**: Expected 1 space before &quot;&gt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore*).

2020-11-26 08:09 UTC, ideaboxgit commented on src/settings/index.js
> +			<App hideLoader = { hideLoader } showLoader = { showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;/&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 08:09 UTC, ideaboxgit commented on src/settings/index.js
> +			<App hideLoader = { hideLoader } showLoader = { showLoader } />,
:no_entry_sign: **Error**: Expected 1 space after &quot;&lt;&quot;; 0 found (*WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter*).

2020-11-26 08:09 UTC, ideaboxgit commented on src/settings/index.js
> +		render(
:no_entry_sign: **Error**: Multi-line function call not indented correctly; expected 4 spaces but found 8 (*PEAR.Functions.FunctionCallSignature.Indent*).

2020-11-26 08:09 UTC, ideaboxgit commented on classes/plugin.php
> +		if ( ! empty( $_POST['nonce'] ) && ! wp_verify_nonce( $_POST['nonce'], 'ibx_ec_infinite_scroll_nonce' ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
:no_entry_sign: **Error**: $_POST data not unslashed before sanitization. Use wp_unslash() or similar (*WordPress.Security.ValidatedSanitizedInput.MissingUnslash*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/coupons-block/coupons-block.php
> + * @param [type] $attributes
:no_entry_sign: **Error**: Missing parameter comment (*Squiz.Commenting.FunctionComment.MissingParamComment*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/coupons-block/coupons-block.php
> + * @param array $options
:no_entry_sign: **Error**: Expected 2 spaces after parameter type; 1 found (*Squiz.Commenting.FunctionComment.SpacingAfterParamType*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/coupons-block/coupons-block.php
> + * @param array $options
:no_entry_sign: **Error**: Missing parameter comment (*Squiz.Commenting.FunctionComment.MissingParamComment*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/coupons-block/coupons-block.php
> + * @param [type] $block Name of the block
:no_entry_sign: **Error**: Parameter comment must end with a full stop (*Squiz.Commenting.FunctionComment.ParamCommentFullStop*).

2020-11-26 08:09 UTC, ideaboxgit requested changes
Previous scan continued.

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.js
> \ No newline at end of file
:warning: **Warning**: File appears to be minified and cannot be processed (*Internal.Tokenizer.Exception*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: File must end with a newline character (*Generic.Files.EndFileNewline.NotFound*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: When a multi-item array uses associative keys, each value should start on a new line (*WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space before array closer (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space after array opener (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener*).

2020-11-26 08:09 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

2020-11-26 08:16 UTC, ideaboxgit requested changes
**phpcs** scanning turned up:

:no_entry_sign: 6 errors 

:warning: 1 warning 

***

**hashes-api**-scanning skipped

2020-11-26 08:16 UTC, ideaboxgit commented on assets/coupons-block/coupons-block.php
> + * @param array $options Additional options.
:no_entry_sign: **Error**: Expected 2 spaces after parameter type; 1 found (*Squiz.Commenting.FunctionComment.SpacingAfterParamType*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.js
> \ No newline at end of file
:warning: **Warning**: File appears to be minified and cannot be processed (*Internal.Tokenizer.Exception*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: File must end with a newline character (*Generic.Files.EndFileNewline.NotFound*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: When a multi-item array uses associative keys, each value should start on a new line (*WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space before array closer (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing space after array opener (*WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener*).

2020-11-26 08:16 UTC, ideaboxgit commented on assets/admin/index.asset.php
> \ No newline at end of file
:no_entry_sign: **Error**: Missing file doc comment (*Squiz.Commenting.FileComment.Missing*).

2020-12-03 12:07 UTC, AchalJ approved these changes

2020-12-03 12:21 UTC, merged